### ISSUE TITLE
这下不得不赞一个了

### ISSUE THREAD

**Issue by fred913** [St7530/LyricsArchive#1]
轴打得绝了，看到一个个音对上的“nanananananananana”人傻了……

**Comment by St7530** [comment]
哈哈，感谢你！

没想到放在GitHub上真的有人看到，有点欣慰了😄

**Comment by fred913** [comment]
在Lyricify上看到的，也是管理员
可以加个qq不？1175882937，交流下，我也蛮喜欢自己打lyricify歌词的（

**Comment by St7530** [comment]
@fred913 已经添加你的QQ了，并且为了避免你的隐私泄露，删除了带有你QQ号的评论。谢谢！
